source "https://rubygems.org"

# frozen_string_literal: true
  gem 'autoprefixer-rails', '~> 10.4', '>= 10.4.19.0'
  gem 'bootstrap', '~>5.3.3'
  gem 'concurrent-ruby', '~>1.3.4'
  gem 'json'
  gem 'faraday', '~>2.12.0'
  gem 'faraday-net_http', '~>3.3.0'
  gem 'faraday-retry', '~>2.2.1'
  gem 'ffi', '~>1.17'
  gem 'google-protobuf', '~>3.25.5'
  gem 'i18n', '~>1.14.6'
  gem 'jekyll'
  gem 'jekyll-sass-converter', '~>3.0.0'
  gem 'jekyll-theme-primer', '~>0.6.0'
  gem 'kramdown'
  gem 'logger', '~>1.6.1'
  gem 'mercenary', '~>0.4.0'
  gem 'octokit', '~>6.1.1'
  gem 'popper_js', '~> 2.11', '>= 2.11.8'
  gem 'public_suffix', '~>6.0.1'
  gem 'rake', '~>13.2.1'
  gem 'rexml', '~>3.3.8'
  gem 'rouge', '~>4.4.0'
  gem 'sass-embedded', '~>1.69.5'
  gem 'sassc', '~>2.4.0'
  gem 'sprockets-rails', '~>2.3.2'
  gem 'terminal-table', '~>3.0.2'
  gem 'unicode-display_width', '~>2.6.0'
  gem 'uri', '~>0.13.1'
  gem 'webrick'
  gemspec
